# services:
#   football_match_analyzer:
#     image: football-match-analyzer:prod
#     container_name: football_match_analyzer
#     environment:
#       - INPUT_VIDEOS_DIR=/app/input_videos
#       - OUTPUT_VIDEOS_DIR=/app/output_videos
#       - STUBS_DIR=/app/stubs
#       - MODELS_DIR=/app/models
#     volumes:
#       - ${PWD}:${PWD}
#       - ${PWD}/input_videos:/app/input_videos
#       - ${PWD}/output_videos:/app/output_videos
#       - ${PWD}/stubs:/app/stubs
#       - ${PWD}/models:/app/models

services:
  football_match_analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: football_match_analyzer
    environment:
      - INPUT_VIDEOS_DIR=/app/input_videos
      - OUTPUT_VIDEOS_DIR=/app/output_videos
      - STUBS_DIR=/app/stubs
      - MODELS_DIR=/app/models
    volumes:
      - ${PWD}:${PWD}
      - ${PWD}/input_videos:/app/input_videos
      - ${PWD}/output_videos:/app/output_videos
      - ${PWD}/stubs:/app/stubs
      - ${PWD}/models:/app/models
